# Generated by Django 4.2.3 on 2023-11-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("is_registered", models.BooleanField(default=False)),
                ("is_startup", models.BooleanField(default=True)),
                ("person_position", models.CharField(max_length=50)),
                ("official_name", models.CharField(max_length=255)),
                ("common_info", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=12)),
                ("edrpou", models.IntegerField()),
                ("founded", models.SmallIntegerField()),
                ("service_info", models.TextField()),
                ("product_info", models.TextField()),
                ("address", models.TextField()),
                ("startup_idea", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authentication.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesActivity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=128)),
                ("name_ua", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="SavedCompany",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_list",
                        to="profiles.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_list_items",
                        to="authentication.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesProfileRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_official", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profilesregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesProfileCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profilescategory",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesProfileActivities",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profilesactivity",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("path", models.CharField(max_length=128)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewedCompany",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.customuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "company")},
            },
        ),
    ]
